# app/config/routing.yml
app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

blog:
    resource: '@AppBundle/Controller/BlogController.php'
    type: annotation

chantier:
    resource: '@AppBundle/Controller/ChantierController.php'
    type: annotation

adresse:
    resource: '@AppBundle/Controller/AdresseController.php'
    type: annotation

document:
    resource: '@AppBundle/Controller/DocumentController.php'
    type: annotation

api:
    resource: '@AppBundle/Controller/ApiController.php'
    type: rest

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

auth0_login:
    path: /auth0/callback

auth0_logout:
    path: /logout/auth0

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /
    defaults: { _format: html } 

oneup_uploader:
    resource: .
    type: uploader