app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gantt:
    path: /demo/planning
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /libs/robicch-jQueryGantt/gantt.html
        permanent: true

oneup_uploader:
    resource: .
    type: uploader