app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
    resource: .
    type: uploader