app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
auth0_login:
    path:    /auth0/callback

auth0_logout:
    path: /auth0/logout

# app/config/routing.yml
# fos_user:
#     resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gantt:
    path: /demo/planning
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /libs/jquery.gantt/gantt.html
        permanent: true

oneup_uploader:
    resource: .
    type: uploader