# app/config/routing.yml
app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

blog:
    resource: '@AppBundle/Controller/BlogController.php'
    type: annotation

btp40_chantier:
    resource: '@AppBundle/Controller/ChantierController.php'
    type: annotation

btp40_chantier_api:
    resource: '@AppBundle/Controller/ApiChantierController.php'
    type: rest
    prefix: /api/chantier

btp40_adresse:
    resource: '@AppBundle/Controller/AdresseController.php'
    type: annotation

btp40_document:
    resource: '@AppBundle/Controller/DocumentController.php'
    type: annotation

btp40_document_api:
    resource: '@AppBundle/Controller/ApiDocumentController.php'
    type: rest
    prefix: /api/document
    
btp40_message_api:
    resource: '@AppBundle/Controller/ApiMessageController.php'
    type: rest
    prefix: /api/message

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

auth0_login:
    path: /auth0/callback

auth0_logout:
    path: /logout/auth0

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comment
    defaults: { _format: html } 

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /demo/message

oneup_uploader:
    resource: .
    type: uploader